# Generated by Django 5.2.3 on 2025-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.URLField()),
                ('Title', models.CharField(max_length=100)),
                ('Warning', models.TextField(max_length=2000)),
                ('Instructions', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='HealthTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.URLField()),
                ('Title', models.CharField(max_length=100)),
                ('Tip', models.TextField(max_length=500)),
                ('Tag', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remedies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.URLField()),
                ('Title', models.CharField(max_length=100)),
                ('Tag', models.CharField(max_length=50)),
                ('Stars', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(max_length=500)),
                ('Ingredients', models.CharField(max_length=400)),
                ('Instructions', models.TextField(max_length=4000)),
                ('HowToUse', models.CharField(max_length=300)),
                ('Precautions', models.CharField(max_length=300)),
            ],
        ),
    ]
